Attribute VB_Name = "TBoolean"
'--------------------------------------
'Global HayCnn As Boolean
Global ServidorMySQL As Boolean
Global ServidorSQLServer As Boolean
Global ServidorSRIPrueba As Boolean
Global ServidorSRIProduccion As Boolean
'-----------------------------------
Global PCActivo As Boolean
Global EstadoUsuario As Boolean
Global SiUnidadEducativa As Boolean
Global ExisteErrores As Boolean
Global SetPapelCopia As Boolean
Global Medio_Rol As Boolean
Global CentroDeCosto As Boolean
Global Num_Meses_CD As Boolean
Global Num_Meses_CE As Boolean
Global Num_Meses_CI As Boolean
Global Num_Meses_ND As Boolean
Global Num_Meses_NC As Boolean
Global CalcComision As Boolean
Global ComisionEjec As Boolean
Global No_Autorizar As Boolean
Global Email_CE_Copia As Boolean
Global Mas_Grupos As Boolean
Global Ret_Aut As Boolean
Global ConSubDir As Boolean
Global Todas_Las_Empresas As Boolean
Global ShiftDown As Boolean
Global AltDown As Boolean
Global CtrlDown As Boolean
Global MenuDeModulos As Boolean
Global OpcCoop As Boolean
Global OpcServicio As Boolean
Global Presentar_Inventario As Boolean
'Global Leyenda_FA As Boolean
Global ConSucursal As Boolean
Global Si_No As Boolean
Global PonerLinea As Boolean
Global Primera_Vez As Boolean
Global Recomen As Boolean
Global Escalas As Boolean
Global Asistencias As Boolean
Global SQL_Server As Boolean
Global SQL_ServerOld As Boolean
Global De_Vencidos As Boolean
Global Individual As Boolean
Global Una_Vez As Boolean
Global Evaluar As Boolean
Global ExpandirPRN As Boolean
Global Empleados As Boolean
Global LlenarRetencion As Boolean
Global PresionarTecla As Boolean
Global PresionoEsc As Boolean
Global Remit As Boolean
Global Benef As Boolean
Global Opcion_Mulp As Boolean
'Global SonidoActivo As Boolean
Global No_Repite As Boolean
Global Si_Repite As Boolean
Global CIConLineas As Boolean
Global CEConLineas As Boolean
Global CDConLineas As Boolean
Global CRConLineas As Boolean
Global LBConLineas As Boolean
Global PGConLineas As Boolean
Global CCHQConLineas As Boolean
Global FAConLineas As Boolean
Global FinBucle As Boolean
Global Bandera As Boolean
Global BanCli As Boolean
Global BanArt As Boolean
Global BanIVA As Boolean
Global Grabar As Boolean
Global Nuevo As Boolean
Global Modificar As Boolean
Global Encontro As Boolean
Global CobroIVA As Boolean
Global TipoGrupo As Boolean
Global LimpiarDiario As Boolean
Global Moneda_US As Boolean
Global IngresarClave As Boolean
Global ResultClaveSup As Boolean
Global Moneda_E As Boolean
Global IniciarPrograma As Boolean
Global FacturaNueva As Boolean
Global FacturaMatricula As Boolean
Global ConciliacionAut As Boolean
Global Mod_Fact As Boolean
Global Mod_Fecha As Boolean
Global Plazo_Fijo As Boolean
'--------------------------------
Global CNivel(1 To 7) As Boolean
Global Supervisor As Boolean
Global ConLibreta As Boolean
Global ExisteComp As Boolean
Global NuevoDiario As Boolean
Global NuevoComp As Boolean
Global CopiarComp As Boolean
Global ModificarComp As Boolean
'--------------------------------
Global OpcCaja As Boolean
Global Mi_Cta As Boolean
Global Alfabetico As Boolean
Global Inv_Promedio As Boolean
Global PVP_Al_Inicio As Boolean
Global InvImp As Boolean
Global CliFact As Boolean
Global Cuadricula As Boolean
Global RUC_Natural As Boolean
Global Copia_PV As Boolean
Global Encabezado_PV As Boolean
Global Grafico_PV As Boolean
Global Cyber_Cabinas As Boolean
Global Parpadear As Boolean
Global ImpCeros As Boolean
Global SinImprimir As Boolean
Global Opc_Primaria As Boolean
Global Opc_Secundaria As Boolean
Global Opc_Bachillerato As Boolean
Global Es_Promedios As Boolean
Global Modo_Educativo As Boolean
Global Encabezado_Prim As Boolean
Global Encabezado_Secu As Boolean
Global Encabezado_Bach As Boolean
Global FA_Educativo As Boolean
'Global File_Emails As Boolean
Global DivisaDiv As Boolean
Global Cierre_Periodo As Boolean
'Global PresentaReloj As Boolean
Global PorCtasCostos As Boolean
Global EsFileCSV As Boolean
