Attribute VB_Name = "TLong"
'-----------------------------------
Global EstadoServidor As Long
Global FechaN As Long
Global FechaIniN As Long
Global FechaFinN As Long
Global PagBarraPrint As Long
Global PorcBarraPrint As Long
Global TotalProceso As Long
Global TotalBarra As Long
Global Contador As Long
Global ContadorRUCCI As Long
Global FondoActual As Long
Global Produccion As Long
Global Sobrantes As Long
Global Faltantes As Long
Global Rotos As Long
Global TotalVentas As Long
Global TotalReg As Long
Global Saldos As Long
'-----------------------------------
Global NumFacturas As Long
Global NumeroLineas As Long
Global ID_Trans As Long
Global ID_Reg As Long
Global Opciones As Long
Global CantLitros As Long
Global DescLitros As Long
Global TotalLitros As Long
Global Litros As Long
Global NumPagos As Long
Global NumDias As Long
Global PosItem As Long
Global i As Long
Global j As Long
Global K As Long
Global F As Long
Global c As Long
Global FechaEntI As Long
Global FechaEntF As Long
Global Nota_No As Long
Global Factura_No As Long
Global Factura_CxP As Long
Global Orden_No As Long
Global DiarioCaja As Long
Global IngresoCaja As Long
Global Factura_Desde As Long
Global Factura_Hasta As Long
Global Asiento As Long
Global NumComp As Long
Global Comp_No As Long
Global NumCompIng As Long
Global NumCompEgr As Long
Global NumCompDia As Long
Global NumeroComp As Long
Global NumRet As Long
Global Numero As Long
Global No_Desde As Long
Global No_Hasta As Long
Global Promedio As Long
Global PromedioLitros As Long
Global Reposicion As Long
Global RegAfectados As Long
Global SaldoProd As Long
Global Cartilla_No As Long
'-----------------------------------
Global V_INCH As Long
Global H_INCH As Long
Global AsignaX As Long
Global AsignaY As Long
Global TipoDatoBusq As Long
Global Solicitud_No As Long
Global NoColor As Long
'-----------------------------------
Global FrameCount As Long
Global TotalFrames As Long
'-----------------------------------
Global Erg As Long
'-----------------------------------
Global RepeatTimes As Long
