Attribute VB_Name = "TCurrency"
Option Explicit
'-----------------------------------
Global MontoAper As Currency
Global MontoCert As Currency
Global SaldoDisp As Currency
Global SaldoCont As Currency
Global TotalAbonos1 As Currency
Global TotalLibreta As Currency
Global TotalCajaMN As Currency
Global TotalCajaME As Currency
Global TotalCajaVa As Currency
Global TotalCredito As Currency
Global TotalSubCta As Currency
Global TotalActivo As Currency
Global TotalPasivo As Currency
Global TotalCapital As Currency
Global TotalIngreso As Currency
Global TotalEgreso As Currency
Global TotalCostos As Currency
Global TotalAbonos As Currency
Global TotalDolar As Currency
Global TotalInteres As Currency
Global TotalComision As Currency
Global TotalEncaje As Currency
Global TotalActivo_ME As Currency
Global TotalPasivo_ME As Currency
Global TotalCapital_ME As Currency
Global TotalIngreso_ME As Currency
Global TotalEgreso_ME As Currency
'-----------------------------
Global SaldoInic As Currency
Global SaldoFinal As Currency
Global SaldoTotal As Currency
Global Suma_ME As Currency
Global Suma_MN As Currency
Global SaldoDebe As Currency
Global SaldoHaber As Currency
Global SumaDebe As Currency
Global SumaHaber As Currency
Global SumaSaldo As Currency
Global SumaCta As Currency
Global SumaBancos As Currency
Global SumaParcial_ME As Currency
Global Debe As Currency
Global Haber As Currency
Global Debe_ME As Currency
Global Haber_ME As Currency
Global Debitos_ME As Currency
Global Creditos_ME As Currency
Global Debitos As Currency
Global Creditos As Currency
Global SaldoActual As Currency
Global SaldoAnterior As Currency
Global SaldoPendiente As Currency
Global Total As Currency
Global Saldo As Currency
Global Total_ME As Currency
Global Saldo_ME As Currency
Global Valor As Currency
Global Valor_ME As Currency
Global ValorDH As Currency
Global ValorTotal As Currency
Global Valor_Habit As Currency
'-----------------------------------
Global Credito As Currency
Global Efectivo As Currency
Global Abono As Currency
Global Abono_ME As Currency
Global Cheque As Currency
Global ChequePosf As Currency
Global Retencion As Currency
'-----------------------------
Global Total_IESS As Currency
Global Total_IESS_Pat As Currency
Global Total_IESS_Per As Currency
Global Total_IESS_Ext As Currency
Global Total_Factura As Currency
Global Total_Servicio As Currency
Global Total_Propinas As Currency
Global Total_FacturaME As Currency
Global Total_Detalle As Currency
Global Total_Sin_IVA As Currency
Global Total_Con_IVA As Currency
Global Total_Sin_No_IVA As Currency
Global Total_SubTotal As Currency
Global Total_Comision As Currency
Global Total_Cobrar As Currency
Global Total_Abonos As Currency
Global Total_Saldos As Currency
Global Total_SubTotal_ME As Currency
Global Total_Comision_ME As Currency
Global Total_Cobrar_ME As Currency
Global Total_Abonos_ME As Currency
Global Total_Saldos_ME As Currency
Global Total_Gastos As Currency
Global Total_Bancos As Currency
Global Total_Cheque As Currency
Global Total_ChequePosf As Currency
Global Total_Pagar As Currency
Global Total_Anticipo As Currency
Global Total_Presupuesto As Currency
Global Total_Interes As Currency
Global Total_Cobranza As Currency
Global Total_Interes_Mora As Currency
Global Total_Desc As Currency
Global Total_Desc2 As Currency
Global Total_Desc_ME As Currency
Global Total_IVA As Currency
Global Total_RetIVA As Currency
Global Total_RetIVAB As Currency
Global Total_RetIVAS As Currency
Global Total_IVA_ME As Currency
Global Total_Ret As Currency
Global Total_RetCta As Currency
Global Total_DetRet As Currency
Global Total_IngCaja As Currency
Global Total_Venta As Currency
Global Total_Tarjeta As Currency
'-----------------------------
Global IVA_NC As Currency
Global SubTotal_NC As Currency
Global SubTotal As Currency
Global SubTotal_IVA As Currency
Global Monto_Total As Currency
Global ValorTotalT As Currency
Global Sumatoria As Currency
Global SumatoriaSC As Currency
Global Diferencia As Currency
Global Caja_ME As Currency
Global Caja_MN As Currency
Global Sueldo_Basico As Currency
Global Canasta_Basica As Currency
'-----------------------------
Global Analitico As Currency
Global Parcial As Currency
Global Parcial_ME As Currency
Global TotalG As Currency
'---------------------------------
Global Nota_Rojo As Currency
Global Mejor_Promedio As Currency
Global Suma_Supletorio As Currency
Global Nota_Mayor As Currency
'---------------------------------
Global Existencia As Currency
Global Entrada As Currency
Global Salida As Currency
Global Stock_Inv As Currency
