Attribute VB_Name = "TSingle"
Global SetPapelAncho As Single
Global SetPapelLargo As Single
'-----------------------------------
Global Interes As Single
Global Tasa As Single
Global Plazo As Single
Global Cuota As Single
Global Porc As Single
Global PorcIVAB As Single
Global PorcIVAS As Single
Global AnchoMenu As Single
Global AltoLetra As Single
Global LongCampo As Single
Global LongVariable As Single
Global LongNumero As Single
Global Distancia As Single
Global Cantidad As Single
Global CantAnterior As Single
Global LimiteAlto As Single
Global LimiteAncho As Single
Global AnchoPapel As Single
Global AnchoMax As Single
Global MargenSup As Single
Global MargenInf  As Single
Global MargenIzq  As Single
Global MargenDer As Single
Global InicioX As Single
Global InicioY As Single
Global PFil As Single
Global PCol As Single
Global PosLinea As Single
Global PosLinea_Aux As Single
Global PosColumna As Single
Global PrimeraLinea As Single
Global UltimaLinea As Single
Global Number As Single
Global Grasa As Single
Global Bonif As Single
Global TotalBonif As Single
Global TotalComAgente As Single
Global TotalComCliente As Single
Global PLitro As Single
Global PLitroT As Single
Global CantidadAnt As Single
Global VUnitAnterior As Single
Global VUnitTemp As Single
Global Comision As Single
Global IESS_Per As Single
Global IESS_Pat As Single
Global IESS_Ext As Single
Global IR As Single
Global JR As Single
Global KR As Single
'-----------------------------------
Global Q_PX As Single
Global Q_EX As Single
'-----------------------------------
Global Cotizacion As Single
Global Dolar As Single
Global Porc_IVA As Single
Global Porc_Serv As Single
'-----------------------------------
Global XMenu1 As Single
Global YMenu1 As Single
Global XMenu2 As Single
Global YMenu2 As Single
Global XMenu3 As Single
Global YMenu3 As Single
Global XMenu4 As Single
Global YMenu4 As Single
Global XMenu5 As Single
Global YMenu5 As Single
Global TiempoServidor As Single
Global TiempoSistema As Single
Global TiempoTarea As Single
Global MiTiempo As Single
Global MiTiempo1 As Single
'-----------------------------------
Global WidthBoolean As Single
Global WidthText As Single
Global WidthDate As Single
Global WidthTime As Single
Global WidthByte As Single
Global WidthLong As Single
Global WidthInteger As Single
Global WidthCurrency As Single
Global WidthSingle As Single
Global WidthDouble  As Single

Global Minutos As Single
Global Segundos As Single
Global Horas As Single

Global MDI_X_Max As Single
Global MDI_Y_Max As Single
'-----------------------------------
