Attribute VB_Name = "TString"
' Variables para conecciones tipo ADO/ADODB/OLE DB
'------------------------------------------------------
Global DescripcionDelServidor As String
Global Nombre_FN_SP As String
Global URLToken As String
Global Token As String
Global MicroEmpresa As String
Global AgenteRetencion As String
Global MascaraCtas As String
Global FormatoCtas As String
Global LimpiarCtas As String
Global URLHTTP As String
Global URLParams As String
Global XML As String
Global HTML As String
'-----------------------------------------
Global strIPServidor As String
Global strNombreBaseDatos As String
Global strWebServices As String
Global strPassword As String
Global strUsuario As String
Global strPuerto As String
'-----------------------------------------
Global AdoStrCnn As String
Global AdoStrCnnBackup As String
'-----------------------------------------
Global PathEmpresa As String
Global PathDataBase As String
Global EmpresaActual As String
Global RutaSistema As String
Global RutaEmpresa As String
Global RutaOrigen As String
Global RutaDestino As String
Global RutaSysBases As String
Global RutaDocumentos As String
Global RutaDocumentoPDF As String
Global RutaEmpresaOld As String
Global RutaCierreEjercicio As String
Global RutaBackup As String
Global RutaUpdate As String
Global RutaSubDirTemp As String
Global HoraSistema As String
Global FechaSistema As String
'-----------------------------------------
Global Fecha_CE As String
Global Fecha_CO As String
Global Fecha_DB As String
Global Fecha_VPN As String
Global Fecha_P12 As String
Global Fecha_update_db As String
Global FechaInicioAnio As String
Global Fecha_Autorizacion As String
Global Fecha_Vence As String
Global Fecha_Retiro As String
Global Fecha_VenceRE As String
Global Fecha_VenceNC As String
Global Fecha_VenceNV As String
Global FechaCorte As String
Global FechaPeriodo As String
Global Fecha_Igualar As String
'-----------------------------------
Global CiudadBenef As String
'-----------------------------------------
Global NombreUsuario As String
Global CodigoUsuario As String
Global IDEUsuario As String
Global PWRUsuario As String
Global Version_Sistema As String
Global SetPapelPRNCad As String
Global SetPRN_2 As String
Global SetPapelPRN_2 As String
Global Modulo As String
Global CajaPV As String
Global SerieFactura As String
Global SerieRet As String
Global SerieNC As String
Global SerieNV As String
Global SerieFE As String
Global CodigoDelBanco As String
Global NombreGerente As String
Global NombreContador As String
Global NombreDocente As String
Global NombreCliente As String
Global Empresa As String
Global Emails As String
Global EmailEmpresa As String
Global EmailUsuario As String
Global EmailContador As String
Global EmailProcesos As String
Global EmailRespaldos As String
Global NombreEntidad As String
Global EstadoEmpresa As String
Global DescripcionEstado As String
Global ComunicadoEntidad As String
Global MensajeEmpresa As String
Global RepresentanteLegal As String
Global Mail_Colegio As String
Global Codigo_AMIE As String
Global Autorizacion As String
Global AutorizaRet As String
Global AutorizaNC As String
Global AutorizaNV As String
Global Rector As String
Global Director As String
Global SexoRector As String
Global SexoDirector As String
Global TextoRector As String
Global TextoVicerrector1 As String
Global TextoVicerrector2 As String
Global TextoDirector As String
Global Secretario1 As String
Global Secretario2 As String
Global Secretario3 As String
Global SexoSecre1 As String
Global SexoSecre2 As String
Global SexoSecre3 As String
Global SexoDocente As String
Global TextoSecretario1 As String
Global TextoSecretario2 As String
Global TextoSecretario3 As String
Global TextoBachiller1 As String
Global TextoBachiller2 As String
Global TextoBachiller3 As String
Global TextoBachiller4 As String
Global Rubro_Matricula As String
Global Anio_Lectivo As String
Global Institucion1 As String
Global Institucion2 As String
Global TextoWeb As String
Global TextoXML As String
Global TextoJSON As String
Global TextoLeyenda As String
Global FormatoLibreta As String
Global RUC As String
Global NombreRUC As String
Global Telefono1 As String
Global Telefono2 As String
Global FAX As String
Global Direccion As String
Global DireccionEstab As String
Global ReferenciaEmpresa As String
Global NombrePais As String
Global NombreCiudad As String
Global NombreProvincia As String
Global CodigoPais As String
Global CodigoPaisEmpleado As String
Global CodigoProv As String
Global FechaCierre As String
Global MsOffice As String
Global TextoFileEmp As String
Global Periodo As String
Global Periodo_Contable As String
Global Periodo_Superior As String
Global NombreComercial As String
Global RazonSocial As String
Global Ambiente As String
Global ContEspec As String
Global Obligado_Conta As String
Global Nombre_Cajero As String
Global RUC_Contador As String
Global CI_Representante As String
Global TID_Repres As String
Global Informativo_FA As String
Global Informativo_FAT As String
Global Debo_Pagare As String
Global No_Patronal As String
Global No_Personal As String
Global No_ATS As String
Global ListSucursales As String
Global MascaraCodigoK As String
Global FormatoCodigoK As String
Global LimpiarCodigoK As String
Global MascaraCurso As String
Global FormatoCurso As String
Global LimpiarCurso As String
Global MascaraCodigoA As String
Global FormatoCodigoA As String
Global LimpiarCodigoA As String
Global MascaraCodigoC As String
Global FormatoCodigoC As String
Global LimpiarCodigoC As String
Global NLogoTipo As String
Global NFirmaDigital As String
Global NMarcaAgua As String
'-----------------------------------------
Global Nombre_Cta_Ret As String
Global Nombres As String
Global Apellidos As String
'===============================================
Global DC_Cobrar As String
Global DC_Ingreso As String
Global DC_Ret_Ingreso As String
Global DC_Ret_Egreso As String
Global DC_IVA As String
Global DC_IVA_Inventario As String
Global DC_Desc As String
Global DC_SubTotal As String
Global DC_Comision As String
Global DC_ComisionB As String
Global DC_Caja As String
Global DC_CajaG As String
Global DC_CajaGE As String
Global DC_CajaBA As String
Global DC_Gastos As String
Global DC_General As String
Global DC_GeneralE As String
Global DC_Ventas As String
Global DC_Ventas_0 As String
Global DC_Costo_Ventas As String
Global DC_Diferencial As String
Global DC_Utilidad As String
Global DC_Inventario As String
Global DC_Faltantes As String
Global DC_Protestos As String
Global DC_Sobrantes As String
Global DC_Suspenso As String
Global DC_Interes As String
Global DC_Interes1 As String
Global DC_Libretas As String
Global DC_Apertura As String
Global DC_Certificado As String
Global DC_Certificado_Apor As String
Global DC_Transito As String
Global DC_Mantenimiento As String
Global DC_Servicio As String
Global DC_Propinas As String
Global DC_Total_Devengado As String
Global DC_Fondo_Emergencia As String
Global DC_Total_Dcts_Aport_Adm As String
Global DC_Total_Dcts_Certif As String
Global DC_Neto_a_Recibir As String
Global DC_Total_Comision As String
Global DC_Total_IESS As String
Global DC_Fondo_Mortuorio As String
Global DC_Servicios_Basicos As String
'=================================================
Global Cta_Cobrar As String
Global Cta_Banco As String
Global Cta_Banco_TJ As String
Global Cta_Del_Banco As String
Global Cta_Bancaria As String
Global Cta_Ingreso As String
Global Cta_Ret As String
Global Cta_Ret_Egreso As String
Global Cta_Ret_IVA As String
Global Cta_Ret_IVA_Egreso As String
Global Cta_CxP_Retenciones As String
Global Cta_IVA As String
Global Cta_IVA_Inventario As String
Global Cta_Desc As String
Global Cta_Desc2 As String
Global Cta_SubTotal As String
Global Cta_Comision As String
Global Cta_ComisionB As String
Global Cta_Aux As String
Global Cta_CajaG As String
Global Cta_CajaGE As String
Global Cta_CajaBA As String
Global Cta_Caja_Vaucher As String
Global Cta_Interes As String
Global Cta_Interes1 As String
Global Cta_Gastos As String
Global Cta_Gastos_Personales As String
Global Cta_General As String
Global Cta_GeneralE As String
Global Cta_Ventas As String
Global Cta_Ventas_0 As String
Global Cta_Ventas_Ant As String
Global Cta_Costo_Ventas As String
Global Cta_Diferencial As String
Global Cta_Utilidad As String
Global Cta_Inventario As String
Global Cta_Faltantes As String
Global Cta_Protestos As String
Global Cta_Sobrantes As String
Global Cta_Suspenso As String
Global Cta_Libretas As String
Global Cta_Apertura As String
Global Cta_Certificado As String
Global Cta_Certificado_Apor As String
Global Cta_Transito As String
Global Cta_Cheque_Transito As String
Global Cta_Solca As String
Global Cta_Intereses As String
Global Cta_Tarjetas As String
Global Cta_Capital As String
Global Cta_Amortizacion As String
Global Cta_Prestamos As String
Global Cta_Impuestos As String
Global Cta_Mantenimiento As String
Global Cta_Servicio As String
Global Cta_Propinas As String
Global Cta_Seguro As String
Global Cta_Seguro_I As String
Global Cta_Provision As String
Global Cta As String
Global Cta1 As String
Global Cta_Sup As String
Global Cta_IESS As String
Global Cta_Devengado As String
Global Cta_Fondo_Emergencia As String
Global Cta_Dcts_Aport_Adm As String
Global Cta_Dcts_Certif As String
Global Cta_Neto_a_Recibir As String
Global Cta_Sueldo As String
Global Cta_Horas_Extras As String
Global Cta_Fondo_Mortuorio As String
Global Cta_Servicios_Basicos As String
Global Cta_Impuesto_Renta_Empleado As String
'============================================
Global Tipo_Cta_Caja As String
Global NombreImagenEsperar As String
Global Contra_Cta As String
Global Contra_Cta1 As String
Global LogoTipo As String
Global LogoTipo1 As String
Global FirmaDigital As String
Global MarcaAgua As String
Global Clave As String
Global ClaveGeneral As String
Global Beneficiario As String
Global Remitente As String
Global Carpeta As String
'-----------------------------------------
Global NivelNo As String
Global NuevaLinea As String
Global TipoFacturas As String
Global SubCtaGen As String
Global SubCtaGen1 As String
Global SubCtaCompCli As String
Global CtaConciliada As String
Global NomCta As String
Global NomCtaSup As String
Global StrgAncho As String
Global StrgFormatoCampo As String
Global StrgFormatoVariable As String
Global BarraPrint As String
Global TextoError As String
Global TextoImprimio As String
Global LineasDeTexto As String
Global CaptionRuta As String
Global TP As String
Global Dia As String
Global Mes As String
Global Anio As String
Global Dia1 As String
Global Mes1 As String
Global Anio1 As String
Global Fecha As String
Global FechaStr As String
Global Mifecha As String
Global MiHora As String
Global MiMes As String
Global MiAnio As String
Global TiempoTexto As String
Global FechaTexto As String
Global HoraTexto As String
Global FechaTexto1 As String
Global FechaComp As String
Global TextoProc As String
Global TextoBanco As String
Global TextoCheque As String
Global TextoFormaPago As String
Global TextoTipoPago As String
Global FechaIni As String
Global FechaFin As String
Global FechaMid As String
Global FechaInicial As String
Global FechaFinal As String
Global FechaMitad As String
Global FechaRespaldo As String
Global T As String
Global ListaFacturas As String
Global Titulo As String
Global ConceptoComp As String
Global DetalleComp As String
Global Mensaje As String
Global Mensajes As String
Global MensajeEncabData As String
Global MensajeEncabado As String
Global Producto As String
Global Cadena As String
Global Cadena1 As String
Global Cadena2 As String
Global Cadena3 As String
Global CodigoA As String
Global CodigoB As String
Global CodigoC As String
Global CodigoD As String
Global CodigoCC As String
Global CodigoN As String
Global CodigoL As String
Global CodigoP As String
Global CodigoT As String
Global Codigos As String
Global Codigo As String
Global Codigo1 As String
Global Codigo2 As String
Global Codigo3 As String
Global Codigo4 As String
Global CodigoDr As String
Global CodigoInv As String
Global CodigoInv1 As String
Global CodigoCli As String
Global CodigoVen As String
Global CodigoCliente As String
Global CodigoEjecutivo As String
Global CodigoBenef As String
Global CodigoBenef2 As String
Global CodigoCorresp As String
Global Codigo_Ministerio As String
'=====================================
Global Cod_CxC As String
Global Cod_Benef As String
Global Cod_Bodega As String
Global Cod_Bodega1 As String
Global Cod_Marca As String
Global Cod_Marca1 As String
Global Cod_Remit As String
Global Cod_Sucur As String
Global Cod_SucurC As String
Global Cod_BenefC As String
Global Cod_Ciudad As String
Global Cod_Pais As String
Global Cod_Base As String
Global Cod_Field As String
Global Cod_Emp As String
Global Cod_NumEmp As String
Global Cod_FechaI As String
Global Cod_FechaF As String
Global Nom_Bodega As String
'======================================
Global DireccionCli As String
Global DireccionGuia As String
Global Recibi_de As String
Global sSQL As String
Global SQL1 As String
Global SQL2 As String
Global SQL3 As String
Global SQL4 As String
Global sSQLTotales As String
Global SQLDec As String
Global SubSQL As String
Global SQLBusq As String
Global SQLMsg1 As String
Global SQLMsg2 As String
Global SQLMsg3 As String
Global SQLMsg4 As String
Global Parametros As String
Global CtaCteNo As String
Global CuentaBanco As String
Global NombreBanco As String
Global CuentaBanco1 As String
Global NombreBanco1 As String
'=====================================
Global TipoBenef As String
Global TipoCta As String
Global TipoComp As String
Global TipoDoc As String
Global TipoProc As String
Global TipoPago As String
Global TipoCtaRet As String
Global TipoCtaBanco As String
Global TipoSubCta As String
Global TipoInventario As String
Global TipoSeteos As String
Global TipoSuper As String
Global TipoFactura As String
Global TipoContribuyente As String
'=====================================
Global Cuenta As String
Global Caracter As String
Global CodSucursal As String
Global Sub_Cuenta As String
Global LetraAnterior As String
Global Dibujo As String
Global msg As String
Global Moneda As String
Global Estado As String
'-----------------------------------
Global SubCta As String
Global Unidad As String
Global Unidad_Temp As String
Global NumStrg As String
Global NumCheque As String
Global Contrato_No As String
Global Habitacion_No As String
Global Cuenta_No As String
Global Credito_No As String
Global Tarjeta_No As String
Global NoCheque As String
Global NombreCampo As String
Global Grupo_No As String
Global DigVerif As String
Global Carta_Porte As String
'-----------------------------------
Global VLocalHost As String
Global VLocalHostName As String
Global VLocalPort As Integer
Global VRemoteHost As String
Global VRemotePort As Integer
Global TextoTraza As String
Global TextoFile As String
Global DirCliente As String
Global TelefCliente As String
Global CICliente As String
'-----------------------------------
Global NumItem As String
Global NumModulo As String
Global NumEmpresa As String
Global NumItemTemp As String
Global GrupoEmpresa As String
'-----------------------------------
Global TextoBusqueda As String
Global CampoBusqueda As String
Global RutaGeneraFile As String
Global NombreArchivo As String
Global SetNombrePRN As String
'-----------------------------------
'Ancho de Tipos Ado
Global CadBoolean As String
Global CadDate As String
Global CadDate1 As String
Global CadTime As String
Global CadByte As String
Global CadInteger As String
Global CadLong As String
Global CadSingle As String
Global CadDouble As String
Global CadCurrency As String
'*** TIPOS DE LETRAS IMPRESORA MATRICIAL
'-----------------------------------------
Global TipoLetra As String
'-----------------------------------------
Global PrintDraft As String
Global Print12CPI As String
Global Print10CPI As String
Global PrintComprimir As String
Global PrintDouble As String
Global PrintNegrita As String
Global PrintAgrandar As String
Global UnPrintComprimir As String
Global UnPrintDouble As String
Global UnPrintNegrita As String
Global UnPrintAgrandar As String
'-----------------------------------------
Global CadenaParcial As String
Global SQLNotas As String
Global SQLTAI As String
Global SQLAIC As String
Global SQLAGC As String
Global SQLL As String
Global SQLProm As String
Global SQLProm1 As String
Global SQLProm2 As String
Global SQLProm3 As String
Global SQLPromQ As String
Global SQLQPX As String
Global SQLQEX As String
Global SQLExaP As String
Global SQLBim1 As String
Global SQLBim2 As String
Global SQLBim3 As String
Global SQLExamen As String
Global SQLConductaQ As String
Global SQLConductaQ1 As String
Global SQLConductaQ2 As String
Global SQLConductaQ3 As String
Global SQLInforme As String
Global OpcionNotas As Byte
Global SQLDias As String
Global CodMat As String
Global CodMatP As String
Global SQLFJ As String
Global SQLFI As String
Global SQLAtrasos As String
Global Evaluacion As String
Global Distrito As String
Global TipoKardex As String
'-----------------------------------------
Global html_Informacion_adicional As String
Global html_Detalle_adicional As String
'-----------------------------------------
Global ListaDeImpresoras() As String
